export const SIMPLE_MAP = {
  а: 'a',
  б: 'b',
  в: 'v',
  г: 'h',
  ґ: 'g',
  д: 'd',
  е: 'e',
  ж: 'zh',
  з: 'z',
  и: 'y',
  і: 'i',
  к: 'k',
  л: 'l',
  м: 'm',
  н: 'n',
  о: 'o',
  п: 'p',
  р: 'r',
  с: 's',
  т: 't',
  у: 'u',
  ф: 'f',
  х: 'kh',
  ц: 'ts',
  ч: 'ch',
  ш: 'sh',
  щ: 'shch',
  ь: '',
  "'": '',
  '’': '',
  ʼ: '',
} satisfies Record<string, string>;

export const POSITIONAL_MAP = {
  є: { start: 'ye', other: 'ie' },
  ї: { start: 'yi', other: 'i' },
  й: { start: 'y', other: 'i' },
  ю: { start: 'yu', other: 'iu' },
  я: { start: 'ya', other: 'ia' },
} satisfies Record<string, { start: string; other: string }>;
